### ISSUE TITLE
Hacky Unlock View

### ISSUE THREAD

**Issue by jonmchan** [jonmchan/pseudo_kiosk#3]
View is really hacky due to rushing to get first version of gem out quickly.

**Problems:**

1. It's ugly (better design template?).
2. ~~All css is in view~~
3. ~~All js is in view~~
4. ~~Failed indication is hacky. ~~

**Todo:**

- [x] CSS in proper `app/assets/stylesheets` location
- [x] Javascript in proper `app/assets/javascript` location

https://github.com/jonmchan/pseudo_kiosk/blob/8600321a702c9c6b0d418f04064099cc5e29bc72/app/views/pseudo_kiosk/authentication/unlock.html.erb

**Comment by m-pereira** [comment]
Can I try to extrac the css?

**Comment by jonmchan** [comment]
hi @m-pereira , thank you for volunteering! You sure can! Submit a PR and I will review your changes.
